/* الإسلام والأوضاع الاقتصادية — ISLAM AND ECONOMIC AFFAIRS — app.js */
/* Based on "Al-Islam wal-Awda' al-Iqtisadiyah" by Sheikh Mohammed al-Ghazali (1917-1996) */

const T={ar:{appTitle:'الإسلام والأوضاع الاقتصادية',splashSub:'العدالة الاقتصادية في ميزان الإسلام',splashHint:'اضغط للتخطي',tabHome:'الرئيسية',tabCards:'البطاقات',tabEcon:'الاقتصاد',tabHabits:'العادات',tabQuiz:'اختبار',tabAbout:'الكتاب',cardsTitle:'الاقتصاد الإسلامي',cardsDesc:'٢٠ درساً عن النظام الاقتصادي في الإسلام — الزكاة وتحريم الربا والعدالة الاجتماعية',econTitle:'مبادئ اقتصادية',econDesc:'كيف عالج الإسلام المشكلات الاقتصادية بعدالة ورحمة',habitsTitle:'عاداتي اليومية',habitsDesc:'عادات اقتصادية إسلامية',quizTitle:'اختبر معرفتك',quizDesc:'ما مدى فهمك للاقتصاد الإسلامي؟',helpTitle:'❓ مساعدة',duaPanelTitle:'🤲 أدعية الرزق',resetBtn:'إعادة تعيين',submitQuiz:'اعرف النتيجة',dailyLabel:'✨ مبدأ اليوم',quizAgain:'أعد الاختبار',share:'مشاركة',searchPlaceholder:'ابحث...',streakMsg:'يوم متتالي!',allDone:'أحسنت!',splashFeatures:['٢٠ درساً في الاقتصاد الإسلامي','مبادئ اقتصادية بحلول عملية','عادات يومية مع تتبع','اختبار معرفة + أدعية الرزق']},
en:{appTitle:'Islam & Economic Affairs',splashSub:'Economic justice in the balance of Islam',splashHint:'tap to skip',tabHome:'Home',tabCards:'Cards',tabEcon:'Economics',tabHabits:'Habits',tabQuiz:'Quiz',tabAbout:'Book',cardsTitle:'Islamic Economics',cardsDesc:'20 lessons on the Islamic economic system — zakat, prohibition of riba, social justice',econTitle:'Economic Principles',econDesc:'How Islam addressed economic problems with justice and mercy',habitsTitle:'My Daily Habits',habitsDesc:'Islamic economic habits',quizTitle:'Test Your Knowledge',quizDesc:'How well do you understand Islamic economics?',helpTitle:'❓ Help',duaPanelTitle:'🤲 Duas for Provision',resetBtn:'Reset Today',submitQuiz:'See Results',dailyLabel:'✨ Today\'s Principle',quizAgain:'Retake Quiz',share:'Share',searchPlaceholder:'Search...',streakMsg:'day streak!',allDone:'Well done!',splashFeatures:['20 lessons on Islamic economics','Economic principles with practical solutions','Daily habits with tracking','Knowledge quiz + provision duas']},
fr:{appTitle:'L\'Islam et les Affaires \u00c9conomiques',splashSub:'La justice \u00e9conomique dans la balance de l\'Islam',splashHint:'appuyez pour passer',tabHome:'Accueil',tabCards:'Cartes',tabEcon:'\u00c9conomie',tabHabits:'Habitudes',tabQuiz:'Quiz',tabAbout:'Livre',cardsTitle:'\u00c9conomie Islamique',cardsDesc:'20 le\u00e7ons sur le syst\u00e8me \u00e9conomique islamique — zakat, interdiction du riba, justice sociale',econTitle:'Principes \u00c9conomiques',econDesc:'Comment l\'Islam a r\u00e9solu les probl\u00e8mes \u00e9conomiques avec justice et mis\u00e9ricorde',habitsTitle:'Mes Habitudes',habitsDesc:'Habitudes \u00e9conomiques islamiques',quizTitle:'Testez Vos Connaissances',quizDesc:'Comprenez-vous l\'\u00e9conomie islamique ?',helpTitle:'❓ Aide',duaPanelTitle:'🤲 Duas pour la Subsistance',resetBtn:'R\u00e9initialiser',submitQuiz:'Voir les R\u00e9sultats',dailyLabel:'✨ Principe du Jour',quizAgain:'Refaire',share:'Partager',searchPlaceholder:'Rechercher...',streakMsg:'jours cons\u00e9cutifs !',allDone:'Bravo !',splashFeatures:['20 le\u00e7ons sur l\'\u00e9conomie islamique','Principes avec solutions pratiques','Habitudes quotidiennes avec suivi','Quiz + duas pour la subsistance']}};

const CARDS=[
{id:1,emoji:'💰',ar:{title:'الزكاة ركن الاقتصاد',desc:'الزكاة ليست صدقة اختيارية بل ركن من أركان الإسلام. هي نظام لتوزيع الثروة يحقق العدالة الاجتماعية ويمنع تكدس المال في أيدي قليلة.',verse:'وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ',verseRef:'سورة البقرة ٢: ٤٣',action:'احسب زكاتك وأخرجها في موعدها'},en:{title:'Zakat: The Economic Pillar',desc:'Zakat is not optional charity but a pillar of Islam. It is a wealth distribution system achieving social justice and preventing wealth accumulation in few hands.',verse:'Establish prayer and give zakat',verseRef:'Surah Al-Baqarah 2:43',action:'Calculate your zakat and pay it on time'},fr:{title:'La Zakat : Pilier \u00c9conomique',desc:'La zakat n\'est pas une charit\u00e9 optionnelle mais un pilier de l\'Islam. C\'est un syst\u00e8me de distribution de richesse assurant la justice sociale.',verse:'\u00c9tablissez la pri\u00e8re et acquittez la zakat',verseRef:'Sourate Al-Baqarah 2:43',action:'Calculez votre zakat et payez-la \u00e0 temps'}},
{id:2,emoji:'🚫',ar:{title:'تحريم الربا',desc:'الربا محرّم في الإسلام لأنه يستغل المحتاج ويزيد الفجوة بين الأغنياء والفقراء. النظام الإسلامي يقوم على المشاركة في الربح والخسارة.',verse:'وَأَحَلَّ اللَّهُ الْبَيْعَ وَحَرَّمَ الرِّبَا',verseRef:'سورة البقرة ٢: ٢٧٥',action:'ابحث عن بدائل إسلامية للقروض الربوية'},en:{title:'Prohibition of Riba (Usury)',desc:'Riba is forbidden in Islam because it exploits the needy and widens the gap between rich and poor. The Islamic system is based on profit and loss sharing.',verse:'Allah has permitted trade and forbidden riba',verseRef:'Surah Al-Baqarah 2:275',action:'Research Islamic alternatives to interest-based loans'},fr:{title:'Interdiction du Riba (Usure)',desc:'Le riba est interdit en Islam car il exploite les n\u00e9cessiteux et creuse le foss\u00e9 entre riches et pauvres. Le syst\u00e8me islamique repose sur le partage des profits et pertes.',verse:'Allah a rendu licite le commerce et interdit le riba',verseRef:'Sourate Al-Baqarah 2:275',action:'Recherchez les alternatives islamiques aux pr\u00eats \u00e0 int\u00e9r\u00eat'}},
{id:3,emoji:'⚖️',ar:{title:'العدالة الاجتماعية',desc:'الإسلام يسعى لتحقيق العدالة الاجتماعية لا المساواة المطلقة. لكل حسب جهده مع ضمان الحد الأدنى الكريم للجميع.',verse:'إِنَّ اللَّهَ يَأْمُرُ بِالْعَدْلِ وَالْإِحْسَانِ',verseRef:'سورة النحل ١٦: ٩٠',action:'ساعد محتاجاً اليوم — ولو بعمل بسيط'},en:{title:'Social Justice',desc:'Islam seeks social justice, not absolute equality. To each according to their effort, while guaranteeing a dignified minimum for all.',verse:'Indeed, Allah commands justice and good conduct',verseRef:'Surah An-Nahl 16:90',action:'Help someone in need today — even with a simple act'},fr:{title:'Justice Sociale',desc:'L\'Islam cherche la justice sociale, pas l\'\u00e9galit\u00e9 absolue. \u00c0 chacun selon son effort, tout en garantissant un minimum digne pour tous.',verse:'Certes, Allah commande la justice et la bienfaisance',verseRef:'Sourate An-Nahl 16:90',action:'Aidez quelqu\'un dans le besoin aujourd\'hui'}},
{id:4,emoji:'🏗️',ar:{title:'أخلاقيات العمل',desc:'العمل في الإسلام عبادة. النبي ﷺ قال: "ما أكل أحد طعاماً قط خيراً من أن يأكل من عمل يده". الإسلام يحارب البطالة والكسل.',verse:'وَقُلِ اعْمَلُوا فَسَيَرَى اللَّهُ عَمَلَكُمْ',verseRef:'سورة التوبة ٩: ١٠٥',action:'أتقن عملك اليوم واعتبره عبادة'},en:{title:'Work Ethics',desc:'Work in Islam is worship. The Prophet ﷺ said: "No one has ever eaten better food than what they earn by the work of their hands." Islam fights unemployment and laziness.',verse:'Say: Work, for Allah will see your deeds',verseRef:'Surah At-Tawbah 9:105',action:'Excel at your work today and consider it worship'},fr:{title:'\u00c9thique du Travail',desc:'Le travail en Islam est une adoration. Le Proph\u00e8te ﷺ a dit : "Personne n\'a jamais mang\u00e9 meilleur que ce qu\'il gagne de ses propres mains."',verse:'Dis : \u0152uvrez, car Allah verra vos actions',verseRef:'Sourate At-Tawbah 9:105',action:'Excellez dans votre travail aujourd\'hui'}},
{id:5,emoji:'🤲',ar:{title:'التكافل الاجتماعي',desc:'الأمة كالجسد الواحد. التكافل يعني أن المجتمع المسلم لا يترك فرداً بلا طعام أو مأوى أو علاج.',verse:'وَتَعَاوَنُوا عَلَى الْبِرِّ وَالتَّقْوَىٰ',verseRef:'سورة المائدة ٥: ٢',action:'شارك في عمل خيري أو تبرع لمحتاج'},en:{title:'Social Solidarity',desc:'The ummah is like one body. Solidarity means the Muslim community does not leave anyone without food, shelter, or treatment.',verse:'Cooperate in righteousness and piety',verseRef:'Surah Al-Ma\'idah 5:2',action:'Participate in charity or donate to someone in need'},fr:{title:'Solidarit\u00e9 Sociale',desc:'La communaut\u00e9 est comme un seul corps. La solidarit\u00e9 signifie ne laisser personne sans nourriture, logement ou soins.',verse:'Entraidez-vous dans la pi\u00e9t\u00e9 et la bienfaisance',verseRef:'Sourate Al-Ma\'idah 5:2',action:'Participez \u00e0 une \u0153uvre caritative ou faites un don'}},
{id:6,emoji:'📊',ar:{title:'توزيع الثروة',desc:'الإسلام يمنع تكدس الثروة في أيدي قلة. الزكاة والميراث والأوقاف أدوات لتوزيع المال بعدالة.',verse:'كَيْ لَا يَكُونَ دُولَةً بَيْنَ الْأَغْنِيَاءِ مِنكُمْ',verseRef:'سورة الحشر ٥٩: ٧',action:'فكر في كيفية توزيع ثروتك بعدل — زكاة وصدقة ووقف'},en:{title:'Wealth Distribution',desc:'Islam prevents wealth hoarding by a few. Zakat, inheritance, and endowments are tools for fair distribution.',verse:'So that wealth does not circulate only among the wealthy',verseRef:'Surah Al-Hashr 59:7',action:'Think about distributing your wealth fairly — zakat, charity, endowments'},fr:{title:'Distribution des Richesses',desc:'L\'Islam emp\u00eache la th\u00e9saurisation par quelques-uns. Zakat, h\u00e9ritage et fondations sont des outils de distribution \u00e9quitable.',verse:'Afin que les richesses ne circulent pas uniquement entre les riches',verseRef:'Sourate Al-Hashr 59:7',action:'R\u00e9fl\u00e9chissez \u00e0 la distribution \u00e9quitable de votre richesse'}},
{id:7,emoji:'🏠',ar:{title:'حق السكن والمأوى',desc:'توفير السكن الكريم مسؤولية الدولة والمجتمع في الإسلام. لا يجوز أن ينام مسلم وجاره جائع.',verse:'مَا آمَنَ بِي مَنْ بَاتَ شَبْعَانَ وَجَارُهُ جَائِعٌ',verseRef:'حديث نبوي',action:'تفقد جيرانك — هل يحتاج أحدهم مساعدة؟'},en:{title:'Right to Housing',desc:'Providing dignified housing is a state and community responsibility in Islam. A Muslim should not sleep full while their neighbor is hungry.',verse:'One who sleeps full while their neighbor is hungry has not believed in me',verseRef:'Prophetic hadith',action:'Check on your neighbors — does anyone need help?'},fr:{title:'Droit au Logement',desc:'Fournir un logement digne est une responsabilit\u00e9 de l\'\u00c9tat et de la communaut\u00e9. Un musulman ne doit pas dormir rassasi\u00e9 alors que son voisin a faim.',verse:'N\'a pas cru en moi celui qui dort rassasi\u00e9 alors que son voisin a faim',verseRef:'Hadith proph\u00e9tique',action:'V\u00e9rifiez si vos voisins ont besoin d\'aide'}},
{id:8,emoji:'🌾',ar:{title:'القضاء على الفقر',desc:'الفقر عدو يجب محاربته. الإسلام يرى أن القضاء على الفقر مسؤولية جماعية وليس مسؤولية الفقير وحده.',verse:'إِنَّمَا الصَّدَقَاتُ لِلْفُقَرَاءِ وَالْمَسَاكِينِ',verseRef:'سورة التوبة ٩: ٦٠',action:'ابحث عن مشروع خيري لمحاربة الفقر وشارك فيه'},en:{title:'Poverty Elimination',desc:'Poverty is an enemy to be fought. Islam sees poverty elimination as a collective responsibility, not just the poor\'s problem.',verse:'Charity is only for the poor and the needy',verseRef:'Surah At-Tawbah 9:60',action:'Find a charity project fighting poverty and participate'},fr:{title:'\u00c9limination de la Pauvret\u00e9',desc:'La pauvret\u00e9 est un ennemi \u00e0 combattre. L\'Islam voit l\'\u00e9limination de la pauvret\u00e9 comme une responsabilit\u00e9 collective.',verse:'Les aum\u00f4nes ne sont que pour les pauvres et les n\u00e9cessiteux',verseRef:'Sourate At-Tawbah 9:60',action:'Trouvez un projet caritatif contre la pauvret\u00e9 et participez'}},
{id:9,emoji:'📜',ar:{title:'الأمانة التجارية',desc:'الصدق والأمانة أساس التجارة في الإسلام. التاجر الأمين مع النبيين والصديقين يوم القيامة.',verse:'وَيْلٌ لِّلْمُطَفِّفِينَ',verseRef:'سورة المطففين ٨٣: ١',action:'كن أميناً في كل تعاملاتك المالية اليوم'},en:{title:'Commercial Integrity',desc:'Honesty and trust are the foundation of trade in Islam. The honest merchant is with the prophets and the truthful on the Day of Judgment.',verse:'Woe to those who give less measure',verseRef:'Surah Al-Mutaffifin 83:1',action:'Be honest in all your financial dealings today'},fr:{title:'Int\u00e9grit\u00e9 Commerciale',desc:'L\'honn\u00eatet\u00e9 et la confiance sont le fondement du commerce en Islam. Le commer\u00e7ant honn\u00eate sera avec les proph\u00e8tes.',verse:'Malheur aux fraudeurs',verseRef:'Sourate Al-Mutaffifin 83:1',action:'Soyez honn\u00eate dans toutes vos transactions financi\u00e8res'}},
{id:10,emoji:'🌍',ar:{title:'الاقتصاد الأخلاقي',desc:'الاقتصاد في الإسلام ليس أرقاماً بل أخلاق. الربح مشروع لكن ليس على حساب الغش والاستغلال.',verse:'يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَأْكُلُوا أَمْوَالَكُم بَيْنَكُم بِالْبَاطِلِ',verseRef:'سورة النساء ٤: ٢٩',action:'راجع تعاملاتك المالية — هل هي كلها حلال؟'},en:{title:'Ethical Economy',desc:'Economics in Islam is not just numbers but ethics. Profit is legitimate but not at the expense of fraud and exploitation.',verse:'O you who believe, do not consume each other\'s wealth unjustly',verseRef:'Surah An-Nisa 4:29',action:'Review your financial dealings — are they all halal?'},fr:{title:'\u00c9conomie \u00c9thique',desc:'L\'\u00e9conomie en Islam n\'est pas que des chiffres mais de l\'\u00e9thique. Le profit est l\u00e9gitime mais pas au d\u00e9triment de la fraude.',verse:'\u00d4 vous qui croyez, ne consommez pas vos biens entre vous de mani\u00e8re illicite',verseRef:'Sourate An-Nisa 4:29',action:'Revoyez vos transactions financi\u00e8res — sont-elles toutes halal ?'}},
{id:11,emoji:'🏦',ar:{title:'البنوك الإسلامية',desc:'البنوك الإسلامية تقوم على المرابحة والمشاركة والمضاربة بدلاً من الفائدة الربوية.',verse:'وَذَرُوا مَا بَقِيَ مِنَ الرِّبَا',verseRef:'سورة البقرة ٢: ٢٧٨',action:'تعرّف على المنتجات المالية الإسلامية المتاحة'},en:{title:'Islamic Banking',desc:'Islamic banks operate through murabaha, musharaka, and mudaraba instead of interest-based lending.',verse:'Give up what remains of riba',verseRef:'Surah Al-Baqarah 2:278',action:'Learn about available Islamic financial products'},fr:{title:'Banques Islamiques',desc:'Les banques islamiques fonctionnent par murabaha, musharaka et mudaraba au lieu du pr\u00eat \u00e0 int\u00e9r\u00eat.',verse:'Renoncez \u00e0 ce qui reste du riba',verseRef:'Sourate Al-Baqarah 2:278',action:'D\u00e9couvrez les produits financiers islamiques disponibles'}},
{id:12,emoji:'🎁',ar:{title:'الصدقة والإنفاق',desc:'الإنفاق في سبيل الله لا ينقص المال بل يباركه. الصدقة تطهر النفس والمال معاً.',verse:'مَّن ذَا الَّذِي يُقْرِضُ اللَّهَ قَرْضًا حَسَنًا فَيُضَاعِفَهُ لَهُ',verseRef:'سورة البقرة ٢: ٢٤٥',action:'تصدّق اليوم ولو بمبلغ صغير'},en:{title:'Charity and Spending',desc:'Spending in God\'s way does not decrease wealth but blesses it. Charity purifies both the soul and the wealth.',verse:'Who will lend Allah a goodly loan so He may multiply it for them?',verseRef:'Surah Al-Baqarah 2:245',action:'Give charity today, even a small amount'},fr:{title:'Charit\u00e9 et D\u00e9penses',desc:'D\u00e9penser dans la voie de Dieu ne diminue pas la richesse mais la b\u00e9nit. La charit\u00e9 purifie l\'\u00e2me et la richesse.',verse:'Qui pr\u00eate \u00e0 Allah un beau pr\u00eat ? Il le lui multipliera',verseRef:'Sourate Al-Baqarah 2:245',action:'Donnez en charit\u00e9 aujourd\'hui, m\u00eame un petit montant'}},
{id:13,emoji:'🤝',ar:{title:'الوقف الإسلامي',desc:'الوقف نظام إسلامي عبقري يحبس الأصل ويوقف الثمرة على وجه من وجوه البر.',verse:'لَن تَنَالُوا الْبِرَّ حَتَّىٰ تُنفِقُوا مِمَّا تُحِبُّونَ',verseRef:'سورة آل عمران ٣: ٩٢',action:'فكر في إنشاء وقف صغير — مكتبة أو بئر ماء'},en:{title:'Islamic Endowment (Waqf)',desc:'Waqf is a genius Islamic system that preserves the asset while dedicating its returns to charitable causes.',verse:'You will not attain piety until you spend from what you love',verseRef:'Surah Aal-Imran 3:92',action:'Consider creating a small endowment — a library or water well'},fr:{title:'Fondation Islamique (Waqf)',desc:'Le waqf est un syst\u00e8me islamique g\u00e9nial qui pr\u00e9serve l\'actif tout en d\u00e9diant ses revenus \u00e0 des causes caritatives.',verse:'Vous n\'atteindrez la pi\u00e9t\u00e9 que si vous d\u00e9pensez de ce que vous aimez',verseRef:'Sourate Aal-Imran 3:92',action:'Pensez \u00e0 cr\u00e9er une petite fondation — biblioth\u00e8que ou puits d\'eau'}},
{id:14,emoji:'👷',ar:{title:'حقوق العمال',desc:'الإسلام كفل حقوق العمال قبل الغرب بقرون. "أعطوا الأجير أجره قبل أن يجف عرقه".',verse:'وَلَا تَبْخَسُوا النَّاسَ أَشْيَاءَهُمْ',verseRef:'سورة هود ١١: ٨٥',action:'إن كنت صاحب عمل، تأكد من دفع الأجور في وقتها'},en:{title:'Workers\' Rights',desc:'Islam guaranteed workers\' rights centuries before the West. "Give the worker his wages before his sweat dries."',verse:'And do not deprive people of their due',verseRef:'Surah Hud 11:85',action:'If you\'re an employer, ensure wages are paid on time'},fr:{title:'Droits des Travailleurs',desc:'L\'Islam a garanti les droits des travailleurs des si\u00e8cles avant l\'Occident. "Donnez au travailleur son salaire avant que sa sueur ne s\u00e8che."',verse:'Et ne l\u00e9sez pas les gens de leurs biens',verseRef:'Sourate Hud 11:85',action:'Si vous \u00eates employeur, assurez-vous que les salaires sont pay\u00e9s \u00e0 temps'}},
{id:15,emoji:'🏛️',ar:{title:'بيت المال',desc:'بيت المال في الإسلام مؤسسة لحفظ أموال الدولة وصرفها في مصارفها الشرعية بعدالة.',verse:'وَالَّذِينَ فِي أَمْوَالِهِمْ حَقٌّ مَّعْلُومٌ',verseRef:'سورة المعارج ٧٠: ٢٤',action:'تعرّف على نظام بيت المال في عهد عمر بن الخطاب'},en:{title:'The Treasury (Bayt al-Mal)',desc:'The Bayt al-Mal in Islam is an institution for preserving state funds and distributing them justly.',verse:'And in whose wealth is a known right',verseRef:'Surah Al-Ma\'arij 70:24',action:'Learn about the treasury system during Umar ibn al-Khattab\'s era'},fr:{title:'Le Tr\u00e9sor (Bayt al-Mal)',desc:'Le Bayt al-Mal en Islam est une institution pour pr\u00e9server les fonds de l\'\u00c9tat et les distribuer justement.',verse:'Et dans leurs biens, il y a un droit connu',verseRef:'Sourate Al-Ma\'arij 70:24',action:'D\u00e9couvrez le syst\u00e8me du tr\u00e9sor sous Umar ibn al-Khattab'}},
{id:16,emoji:'🌱',ar:{title:'القناعة والاكتفاء',desc:'الغنى غنى النفس لا غنى المال. القناعة كنز لا يفنى. المسلم يسعى للرزق الحلال ويقنع بما قسم الله.',verse:'وَلَا تَتَمَنَّوْا مَا فَضَّلَ اللَّهُ بِهِ بَعْضَكُمْ عَلَىٰ بَعْضٍ',verseRef:'سورة النساء ٤: ٣٢',action:'اكتب ٣ نعم مادية تملكها واشكر الله عليها'},en:{title:'Contentment and Sufficiency',desc:'True wealth is wealth of the soul, not money. Contentment is a treasure that never runs out.',verse:'Do not wish for what Allah has favored some of you over others',verseRef:'Surah An-Nisa 4:32',action:'Write 3 material blessings you have and thank God'},fr:{title:'Contentement et Suffisance',desc:'La vraie richesse est celle de l\'\u00e2me, pas l\'argent. Le contentement est un tr\u00e9sor in\u00e9puisable.',verse:'Ne convoitez pas ce qu\'Allah a favoris\u00e9 certains d\'entre vous',verseRef:'Sourate An-Nisa 4:32',action:'\u00c9crivez 3 bienfaits mat\u00e9riels que vous avez et remerciez Dieu'}},
{id:17,emoji:'🚿',ar:{title:'تحريم الإسراف',desc:'الإسراف محرّم حتى في العبادة. الله لا يحب المسرفين. الاعتدال في الإنفاق من أخلاق المسلم.',verse:'وَلَا تُسْرِفُوا إِنَّهُ لَا يُحِبُّ الْمُسْرِفِينَ',verseRef:'سورة الأعراف ٧: ٣١',action:'راقب إنفاقك اليوم — هل فيه إسراف يمكن تجنبه؟'},en:{title:'Prohibition of Extravagance',desc:'Extravagance is forbidden even in worship. God does not love the wasteful. Moderation in spending is a Muslim virtue.',verse:'Do not be extravagant, indeed He does not love the wasteful',verseRef:'Surah Al-A\'raf 7:31',action:'Monitor your spending today — is there avoidable waste?'},fr:{title:'Interdiction du Gaspillage',desc:'Le gaspillage est interdit m\u00eame dans l\'adoration. Dieu n\'aime pas les gaspilleurs. La mod\u00e9ration est une vertu musulmane.',verse:'Ne gaspillez pas, certes Il n\'aime pas les gaspilleurs',verseRef:'Sourate Al-A\'raf 7:31',action:'Surveillez vos d\u00e9penses — y a-t-il du gaspillage \u00e9vitable ?'}},
{id:18,emoji:'🏪',ar:{title:'حرية التجارة',desc:'الإسلام يكفل حرية التجارة والسوق الحر مع ضوابط أخلاقية تمنع الاحتكار والغش.',verse:'يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَأْكُلُوا أَمْوَالَكُم بَيْنَكُم بِالْبَاطِلِ إِلَّا أَن تَكُونَ تِجَارَةً عَن تَرَاضٍ',verseRef:'سورة النساء ٤: ٢٩',action:'تعلّم الضوابط الشرعية للتجارة'},en:{title:'Free Trade',desc:'Islam guarantees free trade with ethical guidelines preventing monopoly and fraud.',verse:'Do not consume wealth unjustly except through trade by mutual consent',verseRef:'Surah An-Nisa 4:29',action:'Learn the Islamic guidelines for trade'},fr:{title:'Libre-\u00c9change',desc:'L\'Islam garantit le libre-\u00e9change avec des directives \u00e9thiques emp\u00eachant le monopole et la fraude.',verse:'Ne consommez pas vos biens de mani\u00e8re illicite sauf par un commerce de consentement mutuel',verseRef:'Sourate An-Nisa 4:29',action:'Apprenez les directives islamiques du commerce'}},
{id:19,emoji:'🌿',ar:{title:'الاقتصاد الأخضر',desc:'الإسلام يحث على حماية البيئة والموارد. النبي ﷺ نهى عن إهدار الماء حتى عند الوضوء.',verse:'وَكُلُوا وَاشْرَبُوا وَلَا تُسْرِفُوا',verseRef:'سورة الأعراف ٧: ٣١',action:'وفّر الماء والكهرباء اليوم — التوفير عبادة'},en:{title:'Green Economy',desc:'Islam encourages protecting the environment and resources. The Prophet ﷺ forbade wasting water even during ablution.',verse:'Eat and drink but do not waste',verseRef:'Surah Al-A\'raf 7:31',action:'Save water and electricity today — saving is worship'},fr:{title:'\u00c9conomie Verte',desc:'L\'Islam encourage la protection de l\'environnement et des ressources. Le Proph\u00e8te ﷺ a interdit le gaspillage d\'eau.',verse:'Mangez et buvez mais ne gaspillez pas',verseRef:'Sourate Al-A\'raf 7:31',action:'\u00c9conomisez l\'eau et l\'\u00e9lectricit\u00e9 aujourd\'hui — \u00e9conomiser est une adoration'}},
{id:20,emoji:'🌏',ar:{title:'رؤية شاملة',desc:'الاقتصاد الإسلامي ليس نظرية أكاديمية بل نظام حياة شامل يحقق العدالة والرحمة والكرامة الإنسانية.',verse:'كُنتُمْ خَيْرَ أُمَّةٍ أُخْرِجَتْ لِلنَّاسِ',verseRef:'سورة آل عمران ٣: ١١٠',action:'شارك مبدأ اقتصادياً إسلامياً مع شخص لا يعرفه'},en:{title:'A Comprehensive Vision',desc:'Islamic economics is not academic theory but a comprehensive life system achieving justice, mercy, and human dignity.',verse:'You are the best nation produced for mankind',verseRef:'Surah Aal-Imran 3:110',action:'Share an Islamic economic principle with someone who doesn\'t know it'},fr:{title:'Une Vision Globale',desc:'L\'\u00e9conomie islamique n\'est pas une th\u00e9orie acad\u00e9mique mais un syst\u00e8me de vie global r\u00e9alisant justice, mis\u00e9ricorde et dignit\u00e9 humaine.',verse:'Vous \u00eates la meilleure communaut\u00e9 produite pour l\'humanit\u00e9',verseRef:'Sourate Aal-Imran 3:110',action:'Partagez un principe \u00e9conomique islamique avec quelqu\'un qui ne le conna\u00eet pas'}}
];

const ECON_DATA=[
{emoji:'💰',ar:{title:'الزكاة تحقق العدالة',text:'الزكاة نظام تكافلي فريد',problem:'٢٦ شخصاً يملكون ثروة نصف البشرية — أزمة عالمية',solution:'لو طُبقت الزكاة لقُضي على الفقر المدقع'},en:{title:'Zakat Achieves Justice',text:'Zakat is a unique solidarity system',problem:'26 people own the wealth of half of humanity — a global crisis',solution:'If zakat were applied, extreme poverty would be eliminated'},fr:{title:'La Zakat R\u00e9alise la Justice',text:'La zakat est un syst\u00e8me de solidarit\u00e9 unique',problem:'26 personnes poss\u00e8dent la richesse de la moiti\u00e9 de l\'humanit\u00e9',solution:'Si la zakat \u00e9tait appliqu\u00e9e, la pauvret\u00e9 extr\u00eame serait \u00e9limin\u00e9e'}},
{emoji:'🚫',ar:{title:'الربا يدمر الاقتصاد',text:'الفوائد الربوية تزيد الأزمات الاقتصادية',problem:'أزمة ٢٠٠٨ سببها الربا والقروض غير المسؤولة',solution:'النظام الإسلامي يقوم على المشاركة في الربح والخسارة — أعدل وأسلم'},en:{title:'Riba Destroys Economies',text:'Interest-based lending increases economic crises',problem:'The 2008 crisis was caused by riba and irresponsible lending',solution:'The Islamic system is based on profit-loss sharing — fairer and safer'},fr:{title:'Le Riba D\u00e9truit les \u00c9conomies',text:'Le pr\u00eat \u00e0 int\u00e9r\u00eat augmente les crises \u00e9conomiques',problem:'La crise de 2008 a \u00e9t\u00e9 caus\u00e9e par le riba et les pr\u00eats irresponsables',solution:'Le syst\u00e8me islamique repose sur le partage des profits et pertes — plus juste et s\u00fbr'}},
{emoji:'⚖️',ar:{title:'العدل لا المساواة المطلقة',text:'الإسلام يميز بين العدل والمساواة',problem:'الشيوعية فشلت لأنها فرضت مساواة مطلقة غير واقعية',solution:'الإسلام يكافئ الجهد ويضمن الحد الأدنى الكريم للجميع'},en:{title:'Justice Not Absolute Equality',text:'Islam distinguishes between justice and equality',problem:'Communism failed by imposing unrealistic absolute equality',solution:'Islam rewards effort while guaranteeing a dignified minimum for all'},fr:{title:'Justice Pas \u00c9galit\u00e9 Absolue',text:'L\'Islam distingue entre justice et \u00e9galit\u00e9',problem:'Le communisme a \u00e9chou\u00e9 en imposant une \u00e9galit\u00e9 absolue irr\u00e9aliste',solution:'L\'Islam r\u00e9compense l\'effort tout en garantissant un minimum digne'}},
{emoji:'🌍',ar:{title:'الاقتصاد الأخلاقي',text:'المال وسيلة لا غاية',problem:'الرأسمالية المتوحشة تجعل المال غاية على حساب الإنسان',solution:'الإسلام يجعل المال خادماً للإنسان لا سيداً عليه'},en:{title:'Ethical Economy',text:'Money is a means, not an end',problem:'Savage capitalism makes money the goal at humanity\'s expense',solution:'Islam makes money serve humanity, not dominate it'},fr:{title:'\u00c9conomie \u00c9thique',text:'L\'argent est un moyen, pas une fin',problem:'Le capitalisme sauvage fait de l\'argent le but aux d\u00e9pens de l\'humanit\u00e9',solution:'L\'Islam fait de l\'argent un serviteur de l\'humanit\u00e9, pas un ma\u00eetre'}},
{emoji:'🤲',ar:{title:'البركة في الحلال',text:'الرزق الحلال مبارك وإن قلّ',problem:'كثيرون يسعون للمال الحرام ظناً أنه يغنيهم',solution:'المال الحلال فيه بركة ونماء — والحرام يُمحق'},en:{title:'Blessing in Halal',text:'Halal provision is blessed even if small',problem:'Many seek haram money thinking it will enrich them',solution:'Halal money has blessing and growth — haram is destroyed'},fr:{title:'B\u00e9n\u00e9diction dans le Halal',text:'La subsistance halal est b\u00e9nie m\u00eame si petite',problem:'Beaucoup cherchent l\'argent haram pensant qu\'il les enrichira',solution:'L\'argent halal est b\u00e9ni et cro\u00eet — le haram est d\u00e9truit'}}
];

const HABITS=[
{emoji:'💰',ar:{label:'ادفع زكاتك أو صدقة',source:'الزكاة'},en:{label:'Pay zakat or charity',source:'Zakat'},fr:{label:'Payez la zakat ou la charit\u00e9',source:'Zakat'}},
{emoji:'🚫',ar:{label:'تجنب المعاملات الربوية',source:'تحريم الربا'},en:{label:'Avoid interest-based deals',source:'Riba prohibition'},fr:{label:'\u00c9vitez les transactions \u00e0 int\u00e9r\u00eat',source:'Interdiction du riba'}},
{emoji:'📿',ar:{label:'ادعُ الله بالرزق الحلال',source:'الدعاء'},en:{label:'Ask God for halal provision',source:'Dua'},fr:{label:'Demandez \u00e0 Dieu une subsistance halal',source:'Dua'}},
{emoji:'🤝',ar:{label:'ساعد محتاجاً',source:'التكافل'},en:{label:'Help someone in need',source:'Solidarity'},fr:{label:'Aidez quelqu\'un dans le besoin',source:'Solidarit\u00e9'}},
{emoji:'💼',ar:{label:'أتقن عملك اليوم',source:'أخلاقيات العمل'},en:{label:'Excel at your work today',source:'Work ethics'},fr:{label:'Excellez dans votre travail',source:'\u00c9thique du travail'}},
{emoji:'🌿',ar:{label:'وفّر الماء والكهرباء',source:'عدم الإسراف'},en:{label:'Save water and electricity',source:'No extravagance'},fr:{label:'\u00c9conomisez l\'eau et l\'\u00e9lectricit\u00e9',source:'Pas de gaspillage'}},
{emoji:'📜',ar:{label:'كن أميناً في تعاملاتك',source:'الأمانة'},en:{label:'Be honest in your dealings',source:'Integrity'},fr:{label:'Soyez honn\u00eate dans vos transactions',source:'Int\u00e9grit\u00e9'}},
{emoji:'🙏',ar:{label:'اشكر الله على رزقك',source:'القناعة'},en:{label:'Thank God for your provision',source:'Contentment'},fr:{label:'Remerciez Dieu pour votre subsistance',source:'Contentement'}}
];

const QUIZ=[
{ar:'هل تحسب زكاتك وتخرجها في وقتها؟',en:'Do you calculate and pay your zakat on time?',fr:'Calculez-vous et payez-vous votre zakat \u00e0 temps ?'},
{ar:'هل تتعامل بالربا في قروضك؟',en:'Do you deal with riba in your loans?',fr:'Utilisez-vous le riba dans vos pr\u00eats ?'},
{ar:'هل تتصدق بانتظام؟',en:'Do you give charity regularly?',fr:'Donnez-vous en charit\u00e9 r\u00e9guli\u00e8rement ?'},
{ar:'هل تسرف في الإنفاق؟',en:'Do you waste in your spending?',fr:'Gaspillez-vous dans vos d\u00e9penses ?'},
{ar:'هل تتقن عملك وتعتبره عبادة؟',en:'Do you excel at work and consider it worship?',fr:'Excellez-vous au travail et le consid\u00e9rez-vous comme adoration ?'},
{ar:'هل تعرف مبادئ الاقتصاد الإسلامي؟',en:'Do you know the principles of Islamic economics?',fr:'Connaissez-vous les principes de l\'\u00e9conomie islamique ?'},
{ar:'هل تتفقد جيرانك المحتاجين؟',en:'Do you check on your neighbors in need?',fr:'V\u00e9rifiez-vous si vos voisins sont dans le besoin ?'},
{ar:'هل تحرص على الكسب الحلال؟',en:'Do you strive for halal earnings?',fr:'Vous efforcez-vous de gagner de mani\u00e8re halal ?'},
{ar:'هل تدخر جزءاً من دخلك؟',en:'Do you save part of your income?',fr:'\u00c9pargnez-vous une partie de vos revenus ?'},
{ar:'هل تعرف الفرق بين البنوك الإسلامية والربوية؟',en:'Do you know the difference between Islamic and conventional banks?',fr:'Connaissez-vous la diff\u00e9rence entre les banques islamiques et conventionnelles ?'}
];

const DUAS=[
{ar:{label:'دعاء الرزق',text:'اللَّهُمَّ إِنِّي أَسْأَلُكَ رِزْقًا طَيِّبًا وَعِلْمًا نَافِعًا وَعَمَلًا مُتَقَبَّلًا',tr:'اللهم إني أسألك رزقاً طيباً وعلماً نافعاً وعملاً متقبلاً'},en:{label:'Dua for Provision',text:'O Allah, I ask You for good provision, beneficial knowledge, and accepted deeds',tr:'O Allah, grant me good provision, beneficial knowledge, and accepted deeds'},fr:{label:'Dua pour la Subsistance',text:'\u00d4 Allah, je Te demande une bonne subsistance, un savoir b\u00e9n\u00e9fique et des actes accept\u00e9s',tr:'\u00d4 Allah, accorde-moi une bonne subsistance'}},
{ar:{label:'دعاء قضاء الدين',text:'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',tr:'اللهم اكفني بحلالك عن حرامك وأغنني بفضلك عمن سواك'},en:{label:'Dua for Debt Relief',text:'O Allah, suffice me with halal over haram and enrich me with Your grace over all others',tr:'O Allah, suffice me with Your lawful provision and enrich me by Your grace'},fr:{label:'Dua pour le Remboursement',text:'\u00d4 Allah, rends-moi suffisant avec le halal et enrichis-moi par Ta gr\u00e2ce',tr:'\u00d4 Allah, rends-moi suffisant avec Ta provision licite'}},
{ar:{label:'دعاء البركة',text:'اللَّهُمَّ بَارِكْ لِي فِي رِزْقِي',tr:'اللهم بارك لي في رزقي وفي أهلي'},en:{label:'Dua for Blessing',text:'O Allah, bless my provision',tr:'O Allah, bless my provision and my family'},fr:{label:'Dua pour la B\u00e9n\u00e9diction',text:'\u00d4 Allah, b\u00e9nis ma subsistance',tr:'\u00d4 Allah, b\u00e9nis ma subsistance et ma famille'}},
{ar:{label:'دعاء الاستغناء',text:'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْفَقْرِ وَالْقِلَّةِ وَالذِّلَّةِ',tr:'اللهم إني أعوذ بك من الفقر والقلة والذلة'},en:{label:'Dua Against Poverty',text:'O Allah, I seek refuge from poverty, scarcity, and humiliation',tr:'O Allah, I seek refuge from poverty, scarcity, and humiliation'},fr:{label:'Dua Contre la Pauvret\u00e9',text:'\u00d4 Allah, je cherche refuge contre la pauvret\u00e9, le manque et l\'humiliation',tr:'\u00d4 Allah, je cherche refuge contre la pauvret\u00e9'}},
{ar:{label:'دعاء التوكل',text:'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ',tr:'حسبي الله لا إله إلا هو عليه توكلت وهو رب العرش العظيم'},en:{label:'Dua of Trust',text:'God suffices me. There is no god but He. In Him I trust.',tr:'He is the Lord of the Great Throne'},fr:{label:'Dua de Confiance',text:'Dieu me suffit. Il n\'y a de dieu que Lui. En Lui je me confie.',tr:'Il est le Seigneur du Tr\u00f4ne immense'}},
{ar:{label:'دعاء الخير',text:'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ',tr:'في الدنيا والآخرة'},en:{label:'Dua for Well-being',text:'O Allah, I ask You for pardon and well-being',tr:'In this world and the next'},fr:{label:'Dua pour le Bien-\u00eatre',text:'\u00d4 Allah, je Te demande le pardon et le bien-\u00eatre',tr:'Ici-bas et dans l\'au-del\u00e0'}}
];

let lang=localStorage.getItem('ie-lang')||'ar';let theme=localStorage.getItem('ie-theme')||'green';const themes=['green','night','garden'];const themeIcons=['💚','🌙','🌿'];const themeNames={green:'💚',night:'🌙 Night',garden:'🌿 Garden'};let currentCardIdx=-1;

document.addEventListener('DOMContentLoaded',()=>{setTheme(theme);setLang(lang);initTabs();initSplash();initScrollTop();renderHome();renderCards();renderEcon();renderHabits();renderQuiz();renderAbout();renderHelp();renderDuas();initScrollReveal();initKeyboardNav();});

function initSplash(){let c=5;const el=document.getElementById('splashCount');const fe=document.getElementById('splashFeatures');if(fe)fe.innerHTML=T[lang].splashFeatures.map((f,i)=>`<div class="splash-feature" style="animation-delay:${0.3+i*0.3}s">${f}</div>`).join('');const iv=setInterval(()=>{c--;if(el)el.textContent=c;if(c<=0){dismissSplash();clearInterval(iv);}},1000);}
function dismissSplash(){const s=document.getElementById('splash');if(s){s.classList.add('hidden');setTimeout(()=>s.style.display='none',500);}playSound('click');}
function setLang(l){lang=l;localStorage.setItem('ie-lang',l);const isRTL=l==='ar';document.documentElement.lang=l;document.documentElement.dir=isRTL?'rtl':'ltr';document.body.dir=isRTL?'rtl':'ltr';document.querySelectorAll('.lang-opt').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));const t=T[l];const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v;};set('appTitle',t.appTitle);set('splashSub',t.splashSub);set('splashHint',t.splashHint);set('tabHome',t.tabHome);set('tabCards',t.tabCards);set('tabEcon',t.tabEcon);set('tabHabits',t.tabHabits);set('tabQuiz',t.tabQuiz);set('tabAbout',t.tabAbout);set('cardsTitle',t.cardsTitle);set('cardsDesc',t.cardsDesc);set('econTitle',t.econTitle);set('econDesc',t.econDesc);set('habitsTitle',t.habitsTitle);set('habitsDesc',t.habitsDesc);set('quizTitle',t.quizTitle);set('quizDesc',t.quizDesc);set('helpTitle',t.helpTitle);set('duaPanelTitle',t.duaPanelTitle);set('habitsReset',t.resetBtn);renderHome();renderCards();renderEcon();renderHabits();renderQuiz();renderAbout();renderHelp();renderDuas();const fe=document.getElementById('splashFeatures');if(fe)fe.innerHTML=T[l].splashFeatures.map((f,i)=>`<div class="splash-feature" style="animation-delay:${0.3+i*0.3}s">${f}</div>`).join('');}
function setTheme(t){theme=t;document.documentElement.dataset.theme=t;localStorage.setItem('ie-theme',t);const idx=themes.indexOf(t);const el=document.getElementById('themeIcon');if(el)el.textContent=themeIcons[idx];}
function cycleTheme(){const idx=(themes.indexOf(theme)+1)%themes.length;setTheme(themes[idx]);showToast(themeNames[themes[idx]]);playSound('theme');}
function initTabs(){document.querySelectorAll('.tab').forEach(tab=>{tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));tab.classList.add('active');const panel=document.getElementById('panel-'+tab.dataset.tab);if(panel)panel.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});playSound('click');});});}
function renderHome(){const t=T[lang];const dayIdx=new Date().getDate()%CARDS.length;const c=CARDS[dayIdx];const cd=c[lang];document.getElementById('dailyCard').innerHTML=`<div class="daily-label">${t.dailyLabel}</div><div class="daily-title">${cd.title}</div><div class="daily-body">${cd.desc}</div><div class="daily-action" onclick="document.querySelector('[data-tab=cards]').click()">${t.tabCards} &#8594;</div>`;const sections=[{icon:'💰',tab:'cards',title:t.tabCards,desc:lang==='ar'?'٢٠ مبدأ اقتصادي':lang==='fr'?'20 principes':'20 principles'},{icon:'📊',tab:'econ',title:t.tabEcon,desc:lang==='ar'?'مبادئ اقتصادية':lang==='fr'?'Principes \u00e9conomiques':'Economic principles'},{icon:'📋',tab:'habits',title:t.tabHabits,desc:lang==='ar'?'عادات يومية':lang==='fr'?'Habitudes':'Habits'},{icon:'🤔',tab:'quiz',title:t.tabQuiz,desc:lang==='ar'?'اختبر نفسك':lang==='fr'?'Testez-vous':'Test yourself'},{icon:'📖',tab:'about',title:t.tabAbout,desc:lang==='ar'?'عن الكتاب':lang==='fr'?'Le livre':'About'}];document.getElementById('homeGrid').innerHTML=sections.map(s=>`<div class="home-card" onclick="document.querySelector('[data-tab=${s.tab}]').click()"><span class="hc-icon">${s.icon}</span><div class="hc-title">${s.title}</div><div class="hc-desc">${s.desc}</div></div>`).join('');}
function renderCards(){const t=T[lang];const sb=`<div class="search-bar"><input type="text" id="cardsSearch" class="search-input" placeholder="${t.searchPlaceholder}" oninput="filterCards(this.value)"><span class="search-icon">🔍</span></div>`;const cards=CARDS.map((c,i)=>{const d=c[lang];return`<div class="principle-card scroll-reveal" id="card-${c.id}" data-search="${d.title.toLowerCase()}"><div class="principle-head" onclick="toggleCard('card-${c.id}')"><span class="principle-num">${c.id}</span><span class="principle-emoji">${c.emoji}</span><span class="principle-title">${d.title}</span><span class="principle-chev">&#9660;</span></div><div class="principle-body"><div class="principle-inner"><p class="principle-desc">${d.desc}</p><div class="verse-box"><div class="verse-arabic">${d.verse}</div><div class="verse-ref">${d.verseRef}</div></div><div class="action-box"><span class="action-icon">💡</span><span>${d.action}</span></div><button class="share-btn" onclick="event.stopPropagation();shareCard(${i})"><span class="share-icon">&#128279;</span> ${t.share}</button></div></div></div>`;}).join('');document.getElementById('cardsContainer').innerHTML=sb+cards;}
function filterCards(q){q=q.toLowerCase().trim();document.querySelectorAll('.principle-card').forEach(c=>{const s=c.dataset.search||'';const t=c.querySelector('.principle-title');c.style.display=(!q||s.includes(q)||(t&&t.textContent.toLowerCase().includes(q)))?'':'none';});}
async function shareCard(idx){const c=CARDS[idx];const d=c[lang];const text=`${c.emoji} ${d.title}\n\n${d.desc}\n\n${d.verse}\n\n💡 ${d.action}\n\n— الإسلام والأوضاع الاقتصادية`;if(navigator.share){try{await navigator.share({title:d.title,text});}catch(e){}}else{try{await navigator.clipboard.writeText(text);showToast('Copied!');}catch(e){}}}
function renderEcon(){document.getElementById('econContainer').innerHTML=ECON_DATA.map(a=>{const d=a[lang];return`<div class="anxiety-card scroll-reveal"><div class="anxiety-header"><span class="anxiety-emoji">${a.emoji}</span><span class="anxiety-title">${d.title}</span></div><div class="verse-box" style="margin-bottom:12px"><div class="verse-arabic">${d.text}</div></div><div class="anxiety-problem"><span class="anxiety-label">${lang==='ar'?'😰 المشكلة':lang==='fr'?'😰 Le Probl\u00e8me':'😰 The Problem'}</span>${d.problem}</div><div class="anxiety-solution"><span class="anxiety-label">${lang==='ar'?'😌 الحل الإسلامي':lang==='fr'?'😌 La Solution Islamique':'😌 The Islamic Solution'}</span>${d.solution}</div></div>`;}).join('');}
function renderHabits(){const today=new Date().toDateString();let hs=JSON.parse(localStorage.getItem('ie-habits')||'{}');if(hs.date!==today){updateStreak(hs);hs={date:today,done:[]};localStorage.setItem('ie-habits',JSON.stringify(hs));}const streak=getStreak();const sh=streak>0?`<div class="streak-badge">🔥 ${streak} ${T[lang].streakMsg}</div>`:'';document.getElementById('habitsContainer').innerHTML=HABITS.map((h,i)=>{const d=h[lang];const done=hs.done.includes(i);return`<div class="habit-item ${done?'done':''}" onclick="toggleHabit(${i})"><span class="habit-check">${done?'&#10003;':''}</span><span class="habit-emoji">${h.emoji}</span><div><div class="habit-label">${d.label}</div><div class="habit-source">${d.source}</div></div></div>`;}).join('');const se=document.getElementById('streakBadge');if(se)se.innerHTML=sh;updateHabitsProgress(hs);}
function toggleHabit(i){const today=new Date().toDateString();let hs=JSON.parse(localStorage.getItem('ie-habits')||'{}');if(hs.date!==today)hs={date:today,done:[]};const idx=hs.done.indexOf(i);if(idx>-1)hs.done.splice(idx,1);else hs.done.push(i);localStorage.setItem('ie-habits',JSON.stringify(hs));renderHabits();playSound(idx>-1?'click':'success');if(hs.done.length===HABITS.length){launchConfetti();showToast(T[lang].allDone);}}
function resetHabits(){localStorage.setItem('ie-habits',JSON.stringify({date:new Date().toDateString(),done:[]}));renderHabits();showToast(lang==='ar'?'تم':'Reset');}
function updateHabitsProgress(hs){const d=hs.done.length,t=HABITS.length,p=t>0?(d/t*100):0;const f=document.getElementById('habitsFill');const tx=document.getElementById('habitsText');if(f)f.style.width=p+'%';if(tx)tx.textContent=`${d}/${t}`;}
function updateStreak(ps){let sd=JSON.parse(localStorage.getItem('ie-streak')||'{"count":0,"lastDate":""}');if(ps&&ps.done&&ps.done.length===HABITS.length&&ps.date){const y=new Date();y.setDate(y.getDate()-1);if(ps.date===y.toDateString())sd.count++;else if(ps.date!==new Date().toDateString())sd.count=ps.done.length===HABITS.length?1:0;sd.lastDate=ps.date;}else if(ps&&ps.date){sd.count=0;sd.lastDate=ps.date;}localStorage.setItem('ie-streak',JSON.stringify(sd));}
function getStreak(){return JSON.parse(localStorage.getItem('ie-streak')||'{"count":0}').count;}
function launchConfetti(){const canvas=document.getElementById('confettiCanvas');if(!canvas)return;canvas.style.display='block';const ctx=canvas.getContext('2d');canvas.width=window.innerWidth;canvas.height=window.innerHeight;const ps=[];const colors=['#1B5E20','#4CAF50','#81C784','#C8E6C9','#FFD54F','#A5D6A7'];for(let i=0;i<120;i++)ps.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height-canvas.height,w:Math.random()*10+5,h:Math.random()*6+3,color:colors[Math.floor(Math.random()*colors.length)],vx:(Math.random()-0.5)*4,vy:Math.random()*3+2,rot:Math.random()*360,rotSpeed:(Math.random()-0.5)*10});let frame=0;function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ps.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.rot+=p.rotSpeed;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot*Math.PI/180);ctx.fillStyle=p.color;ctx.fillRect(-p.w/2,-p.h/2,p.w,p.h);ctx.restore();});frame++;if(frame<120)requestAnimationFrame(draw);else{ctx.clearRect(0,0,canvas.width,canvas.height);canvas.style.display='none';}}draw();}
function renderQuiz(){const t=T[lang];document.getElementById('quizContainer').innerHTML=QUIZ.map((q,i)=>`<div class="quiz-question scroll-reveal" id="quiz-q-${i}"><div class="quiz-q-text">${i+1}. ${q[lang]}</div><div class="quiz-options"><button class="quiz-opt" onclick="selectQuizOpt(${i},2)">${lang==='ar'?'نعم':lang==='fr'?'Oui':'Yes'}</button><button class="quiz-opt" onclick="selectQuizOpt(${i},1)">${lang==='ar'?'أحياناً':lang==='fr'?'Parfois':'Sometimes'}</button><button class="quiz-opt" onclick="selectQuizOpt(${i},0)">${lang==='ar'?'لا':lang==='fr'?'Non':'No'}</button></div></div>`).join('')+`<button class="quiz-submit" onclick="submitQuiz()">${t.submitQuiz}</button>`;document.getElementById('quizResult').classList.add('hidden');window._quizAnswers={};}
function selectQuizOpt(qi,v){window._quizAnswers[qi]=v;document.querySelectorAll(`#quiz-q-${qi} .quiz-opt`).forEach((o,oi)=>o.classList.toggle('selected',[2,1,0][oi]===v));playSound('click');}
function submitQuiz(){const a=window._quizAnswers||{};if(Object.keys(a).length<QUIZ.length){showToast(lang==='ar'?'أجب على جميع الأسئلة':'Answer all');return;}const inv=[1,3];let score=0;Object.entries(a).forEach(([qi,v])=>{score+=inv.includes(parseInt(qi))?(2-v):v;});const max=QUIZ.length*2;const pct=Math.round(score/max*100);let emoji,title,desc;if(pct>=75){emoji='💰';title=lang==='ar'?'خبير اقتصادي!':'Economic expert!';desc=lang==='ar'?'فهمك للاقتصاد الإسلامي ممتاز!':'Your understanding of Islamic economics is excellent!';}else if(pct>=50){emoji='📊';title=lang==='ar'?'جيد':'Good';desc=lang==='ar'?'معرفتك جيدة — واصل التعلم':'Your knowledge is good — keep learning';}else{emoji='📖';title=lang==='ar'?'ابدأ التعلم!':'Start learning!';desc=lang==='ar'?'تحتاج قراءة أكثر عن الاقتصاد الإسلامي':'You need to read more about Islamic economics';}const r=document.getElementById('quizResult');r.classList.remove('hidden');r.innerHTML=`<div class="qr-emoji">${emoji}</div><div class="qr-score">${pct}%</div><div class="qr-title">${title}</div><div class="qr-desc">${desc}</div><button class="quiz-submit" onclick="renderQuiz()" style="margin-top:16px">${T[lang].quizAgain}</button>`;r.scrollIntoView({behavior:'smooth'});playSound('success');}
function renderAbout(){const about={ar:{disclaimerTitle:'⚠️ تنبيه مهم',disclaimer:'لست عالماً ولا مفتياً. هذا جهد متواضع من مسلم يحب كتب الشيخ الغزالي. ليست فتوى.',authorName:'الشيخ محمد الغزالي',authorDates:'١٩١٧ — ١٩٩٦',authorBio:'عالم ومفكر إسلامي مصري، لُقب بـ"أديب الدعوة". ألّف أكثر من ٩٤ كتاباً.',bookTitle:'عن الكتاب',bookDesc:'كتاب "الإسلام والأوضاع الاقتصادية" يستعرض فيه الشيخ الغزالي النظام الاقتصادي في الإسلام ويبين أنه نظام عادل وسطي بين الرأسمالية المتوحشة والشيوعية القمعية.',sourcesTitle:'المصادر',sources:['كتاب "الإسلام والأوضاع الاقتصادية" — الشيخ محمد الغزالي','القرآن الكريم','صحيح البخاري ومسلم'],contact:'تواصل: abdelhak.bourdim@gmail.com'},en:{disclaimerTitle:'⚠️ Important Notice',disclaimer:'I am not a scholar. This is a humble effort by a Muslim who loves Sheikh al-Ghazali\'s books. Not a fatwa.',authorName:'Sheikh Mohammed al-Ghazali',authorDates:'1917 — 1996',authorBio:'Egyptian Islamic scholar and thinker. Author of 94+ books.',bookTitle:'About the Book',bookDesc:'"Islam and Economic Affairs" explores the Islamic economic system, showing it as a just middle way between savage capitalism and oppressive communism.',sourcesTitle:'Sources',sources:['"Islam and Economic Affairs" — Sheikh Mohammed al-Ghazali','The Holy Quran','Sahih al-Bukhari and Muslim'],contact:'Contact: abdelhak.bourdim@gmail.com'},fr:{disclaimerTitle:'⚠️ Avis Important',disclaimer:'Je ne suis ni savant ni mufti. Effort humble. Pas une fatwa.',authorName:'Sheikh Mohammed al-Ghazali',authorDates:'1917 — 1996',authorBio:'Savant islamique \u00e9gyptien. Auteur de 94+ livres.',bookTitle:'\u00c0 Propos du Livre',bookDesc:'\u00ab L\'Islam et les Affaires \u00c9conomiques \u00bb explore le syst\u00e8me \u00e9conomique islamique, le montrant comme une voie juste entre le capitalisme sauvage et le communisme oppressif.',sourcesTitle:'Sources',sources:['\u00ab L\'Islam et les Affaires \u00c9conomiques \u00bb — Sheikh al-Ghazali','Le Saint Coran','Sahih al-Bukhari et Muslim'],contact:'Contact : abdelhak.bourdim@gmail.com'}};const a=about[lang];document.getElementById('aboutContainer').innerHTML=`<div class="about-disclaimer"><div class="about-disclaimer-title">${a.disclaimerTitle}</div><p>${a.disclaimer}</p></div><div class="about-author"><span class="about-author-icon">📚</span><div class="about-author-info"><div class="about-author-name">${a.authorName}</div><div class="about-author-dates">${a.authorDates}</div><div class="about-author-bio">${a.authorBio}</div></div></div><div class="about-section"><div class="about-section-title">${a.bookTitle}</div><p class="about-text">${a.bookDesc}</p></div><div class="about-section"><div class="about-section-title">${a.sourcesTitle}</div>${a.sources.map(s=>`<p class="about-text">&#8226; ${s}</p>`).join('')}</div><div class="about-section"><p class="about-text">${a.contact}</p></div>`;}
function renderHelp(){const h={ar:[{title:'⚠️ تنبيه',body:'لست عالماً. هذا جهد متواضع.'},{title:'📚 المصادر',body:'كتاب "الإسلام والأوضاع الاقتصادية" للشيخ محمد الغزالي.'},{title:'✨ المميزات',body:'٣ لغات، ٣ أنماط، ٢٠ بطاقة، مبادئ اقتصادية، عادات، اختبار، أدعية.'}],en:[{title:'⚠️ Disclaimer',body:'I am not a scholar.'},{title:'📚 Sources',body:'"Islam and Economic Affairs" by Sheikh al-Ghazali.'},{title:'✨ Features',body:'3 languages, 3 themes, 20 cards, economic principles, habits, quiz, duas.'}],fr:[{title:'⚠️ Avertissement',body:'Je ne suis pas un savant.'},{title:'📚 Sources',body:'\u00ab L\'Islam et les Affaires \u00c9conomiques \u00bb.'},{title:'✨ Fonctionnalit\u00e9s',body:'3 langues, 3 th\u00e8mes, 20 cartes, principes, habitudes, quiz, duas.'}]};document.getElementById('helpBody').innerHTML=h[lang].map(i=>`<div class="help-item"><div class="help-item-title">${i.title}</div><div>${i.body}</div></div>`).join('');}
function renderDuas(){document.getElementById('duaPanelContent').innerHTML=DUAS.map(d=>{const dd=d[lang];return`<div class="dua-item"><div class="dua-item-label">${dd.label}</div><div class="dua-item-ar">${dd.text}</div><div class="dua-item-tr">${dd.tr}</div></div>`;}).join('');}
function initScrollReveal(){if(!('IntersectionObserver' in window))return;const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');obs.unobserve(e.target);}});},{threshold:0.08,rootMargin:'0px 0px -40px 0px'});function oa(){document.querySelectorAll('.scroll-reveal:not(.revealed)').forEach(el=>obs.observe(el));}oa();document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>setTimeout(oa,100)));}
function initKeyboardNav(){document.addEventListener('keydown',e=>{if(e.key==='Escape'){const hp=document.getElementById('helpPanel');if(!hp.classList.contains('hidden')){toggleHelp();return;}const dp=document.getElementById('duaPanel');if(!dp.classList.contains('hidden')){toggleDuaPanel();return;}document.querySelectorAll('.principle-card.open').forEach(c=>c.classList.remove('open'));}if(e.key==='ArrowRight'||e.key==='ArrowLeft'){const cp=document.getElementById('panel-cards');if(!cp||!cp.classList.contains('active'))return;e.preventDefault();const cards=Array.from(document.querySelectorAll('.principle-card')).filter(c=>c.style.display!=='none');if(!cards.length)return;if(currentCardIdx>=0&&currentCardIdx<cards.length)cards[currentCardIdx].classList.remove('open');const dir=(document.documentElement.dir==='rtl')?(e.key==='ArrowRight'?-1:1):(e.key==='ArrowRight'?1:-1);currentCardIdx=Math.max(0,Math.min(cards.length-1,currentCardIdx+dir));cards[currentCardIdx].classList.add('open');cards[currentCardIdx].scrollIntoView({behavior:'smooth',block:'center'});playSound('click');}});}
function toggleCard(id){const c=document.getElementById(id);if(c){c.classList.toggle('open');playSound('click');}}
function toggleHelp(){document.getElementById('helpPanel').classList.toggle('hidden');playSound('click');}
function toggleDuaPanel(){document.getElementById('duaPanel').classList.toggle('hidden');playSound('click');}
function showToast(msg){const t=document.getElementById('toast'),m=document.getElementById('toastMsg');if(t&&m){m.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',2500);}}
function initScrollTop(){const btn=document.getElementById('scrollTop');window.addEventListener('scroll',()=>{if(btn)btn.classList.toggle('visible',window.scrollY>300);});}
const AudioCtx=window.AudioContext||window.webkitAudioContext;let audioCtx;
function playSound(type){try{if(!audioCtx)audioCtx=new AudioCtx();const osc=audioCtx.createOscillator();const gain=audioCtx.createGain();osc.connect(gain);gain.connect(audioCtx.destination);gain.gain.value=0.06;if(type==='click'){osc.frequency.value=800;osc.type='sine';gain.gain.value=0.04;}else if(type==='success'){osc.frequency.value=523;osc.type='sine';}else if(type==='theme'){osc.frequency.value=440;osc.type='triangle';gain.gain.value=0.05;}osc.start();osc.stop(audioCtx.currentTime+0.1);}catch(e){}}
(function(){let sx=0,sy=0;const to=['home','cards','econ','habits','quiz','about'];document.addEventListener('touchstart',e=>{sx=e.changedTouches[0].screenX;sy=e.changedTouches[0].screenY;},{passive:true});document.addEventListener('touchend',e=>{const dx=e.changedTouches[0].screenX-sx;const dy=e.changedTouches[0].screenY-sy;if(Math.abs(dx)<80||Math.abs(dy)>Math.abs(dx)*0.7)return;const ct=document.querySelector('.tab.active');if(!ct)return;const ci=to.indexOf(ct.dataset.tab);if(ci<0)return;const isRTL=document.documentElement.dir==='rtl';let ni;if(dx>0)ni=isRTL?Math.min(ci+1,to.length-1):Math.max(ci-1,0);else ni=isRTL?Math.max(ci-1,0):Math.min(ci+1,to.length-1);if(ni!==ci)document.querySelector(`.tab[data-tab="${to[ni]}"]`).click();},{passive:true});})();
